### ISSUE TITLE
After I upload the file, I get the following error

### ISSUE THREAD

**Issue by chappyhome** [ciocan/langchain-chat-with-documents#2]
Error: 'Error in addDocuments' FetchError: request to https://https//chappyhome-ea1f2qjp.weaviate.network%20#%20do%20not%20use%20https://%20just%20the%20domain%20like%20bellingcat-xxx.weaviate.network/v1/batch/objects failed, reason: getaddrinfo ENOTFOUND https
    at WeaviateStore.addVectors (file:///root/ai/langchain-chat-with-documents/node_modules/langchain/dist/vectorstores/weaviate.js:103:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WeaviateStore.fromDocuments (file:///root/ai/langchain-chat-with-documents/node_modules/langchain/dist/vectorstores/weaviate.js:155:9)
    at async eval (webpack-internal:///(api)/./src/server/api/routers/weaviate.ts:80:13)
    at async resolveMiddleware (file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/index.mjs:416:30)
    at async callRecursive (file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/index.mjs:452:32)
    at async callRecursive (file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/index.mjs:452:32)
    at async resolve (file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/index.mjs:482:24)
    at async file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/resolveHTTPResponse-e1286cb3.mjs:87:32
    at async Promise.all (index 0)
    at async resolveHTTPResponse (file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/resolveHTTPResponse-e1286cb3.mjs:84:28)
    at async file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-f0efcff4.mjs:32:24
    at async file:///root/ai/langchain-chat-with-documents/node_modules/@trpc/server/dist/adapters/next.mjs:42:9
❌ tRPC failed on weaviate.index: Failed to index document

**Comment by Moh-Adel-Aly** [comment]
Remove the http// from your WEAVIATE_HOST and remove the commented line after it. Starting from the #
